package com.geek45.infra.dal.table.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   字段配置表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table gk_table_config
 */
public class TableConfigDO {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_create")
    private Long gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_modify")
    private Long gmtModify;

    /**
     * Database Column Remarks:
     *   创建用户
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.creator")
    private String creator;

    /**
     * Database Column Remarks:
     *   修改用户
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.modifier")
    private String modifier;

    /**
     * Database Column Remarks:
     *   逻辑删除字段。1:未删除，0：已删除
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.deleted")
    private Boolean deleted;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.version")
    private Integer version;

    /**
     * Database Column Remarks:
     *   字段标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.name")
    private String name;

    /**
     * Database Column Remarks:
     *   展示名字
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.label")
    private String label;

    /**
     * Database Column Remarks:
     *   类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.type")
    private String type;

    /**
     * Database Column Remarks:
     *   排序
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.sort")
    private Integer sort;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_create")
    public Long getGmtCreate() {
        return gmtCreate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_create")
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_modify")
    public Long getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.gmt_modify")
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.creator")
    public String getCreator() {
        return creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.modifier")
    public String getModifier() {
        return modifier;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.modifier")
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.deleted")
    public Boolean getDeleted() {
        return deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.deleted")
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.version")
    public Integer getVersion() {
        return version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.version")
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.label")
    public String getLabel() {
        return label;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.label")
    public void setLabel(String label) {
        this.label = label;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.type")
    public String getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.type")
    public void setType(String type) {
        this.type = type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.sort")
    public Integer getSort() {
        return sort;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: gk_table_config.sort")
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: gk_table_config")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", creator=").append(creator);
        sb.append(", modifier=").append(modifier);
        sb.append(", deleted=").append(deleted);
        sb.append(", version=").append(version);
        sb.append(", name=").append(name);
        sb.append(", label=").append(label);
        sb.append(", type=").append(type);
        sb.append(", sort=").append(sort);
        sb.append("]");
        return sb.toString();
    }
}